default:
  type: node
  screens:
  - name: index
    backgroundImage: true

    regions:
    - className: page-nav
      components:
      - PageNav

    - scrollable: true
      components:
      - PageHeaderImage
      - BodyText
      - ChildNodes
