Default:
  type: node
  screens:
  - name: index
    layoutName: default
    backgroundImage: true
    regions:
    - size: fixed
      components:
      - PageNav
    - scrollable: true
      components:
      - PageHeaderImage
      - BodyText
      - ChildNodes
